spring.application.name=HRManagementSystem

server.port=8081

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=HRManagementSystem;encrypt=true;trustServerCertificate=true
spring.datasource.username=hradmin
spring.datasource.password=hradmin123!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Show SQL parameter binding values in logs (great for debugging queries)
logging.level.org.hibernate.orm.jdbc.bind=trace
jwt.secret=404E635266556A58SE3272358F98782F413F4428472B4B6250655368566D5973
jwt.expiration=3600000
